#!/usr/bin/env bash
# One-time setup for a fresh Ubuntu droplet. Run from the repo root, after cloning:
#
#   git clone <your-repo-url> abacus-scraper && cd abacus-scraper
#   bash deploy/setup.sh
#
# Safe to re-run - each step either checks first or overwrites its own prior output
# (the crontab step replaces only its own two lines, never anything else you have
# scheduled). Does NOT create .env: secrets aren't something a script should
# generate or fetch on its own - copy your local .env over by hand (e.g. `scp
# .env droplet:abacus-scraper/.env`) after this runs.
set -euo pipefail

REPO_DIR="$(pwd)"
if [ ! -f "$REPO_DIR/requirements.txt" ]; then
    echo "Run this from the repo root (requirements.txt not found here)." >&2
    exit 1
fi

echo "== Installing uv (manages Python 3.14 - Ubuntu's own python3 is 3.12) =="
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

echo "== Installing Python 3.14 and creating the venv =="
uv python install 3.14
uv venv --python 3.14 "$REPO_DIR/.venv"
# shellcheck disable=SC1091
source "$REPO_DIR/.venv/bin/activate"
uv pip install -r "$REPO_DIR/requirements.txt"

echo "== Setting system timezone to America/New_York =="
# kickoff_windows()'s timestamps are naive and assumed Eastern (see
# nfl_source.py). Running cron itself in Eastern means the schedule below can use
# plain wall-clock times instead of a per-line TZ= hack.
sudo timedatectl set-timezone America/New_York

echo "== Configuring git identity for this repo (needed for automated commits) =="
# schedule_captures.py commits captured data back to git after each capture (see
# sync_captured_data()) - a commit needs an identity to attribute to. Repo-local
# only (no --global), and only set if not already configured.
git config user.email >/dev/null 2>&1 || git config user.name >/dev/null 2>&1 || {
    git config user.name "${GIT_AUTHOR_NAME:-nfl-props droplet}"
    git config user.email "${GIT_AUTHOR_EMAIL:-droplet@localhost}"
}

echo "== Installing crontab entries =="
# schedule_captures.py: polls every 15 min, no-ops unless a kickoff window is
# actually due (see its own docstring) - cheap and safe to run this often.
# scorecard.py --push: once a week, Tuesday morning, well after Monday Night
# Football has finished and actuals have published.
CRON_MARKER="# abacus-scraper (managed by deploy/setup.sh - do not hand-edit these two lines)"
CRON_CAPTURE="*/15 * * * * cd $REPO_DIR && $REPO_DIR/.venv/bin/python schedule_captures.py >> $REPO_DIR/scheduler.log 2>&1"
CRON_SCORECARD="0 9 * * 2 cd $REPO_DIR && $REPO_DIR/.venv/bin/python scorecard.py --push >> $REPO_DIR/scorecard.log 2>&1"

(crontab -l 2>/dev/null | grep -v "abacus-scraper"; \
 echo "$CRON_MARKER"; echo "$CRON_CAPTURE"; echo "$CRON_SCORECARD") | crontab -

echo ""
echo "Done. Remaining manual steps:"
echo "  1. Copy your .env into $REPO_DIR/.env (never committed, never generated by this script)."
echo "  2. Verify: cd $REPO_DIR && .venv/bin/python -m pytest tests/ -q"
echo "  3. Check the crontab: crontab -l"
